### PR TITLE
Rework Tech101 slides with more exercises and shorter format

### PR DESCRIPTION
**Pull request by angelacastanieto**
Rework Tech101 slides with more exercises and shorter format

Here's a description of changes:

* Change example webpage to https://allaboutdogs-tech101.herokuapp.com/ which was specifically created for this lecture
* Change content and outline of slides
* Remove unused images and add new images

cc @gdisf/admins

### CODE REVIEW

**Comment by brendajin** [comment]
Overall, I love how you have condensed the material and added hands-on exercises! 

One high-level comment I have is that these slides need to stand alone for future reference. Is there any way to animate the images or provide notes or some short text on visual-only slides for people to understand what's happening?

**Comment by brendajin** [comment]
Another question about this repo – do you have a script to reset the DB after class?

**Comment by angelacastanieto** [comment]
@brendajin The slide notes are in the html code as <aside/>

From what I read in the docs, when you hit 's' as you're on the slides, the notes pop up.  Once I meet with @chatasweetie tomorrow we'll come up with more thorough text for these asides and we can update

**Comment by angelacastanieto** [comment]
@brendajin regarding the reset script, I'll write one and and add it to the repo

**Comment by angelacastanieto** [comment]
@brendajin I can see if I can animate the images and show gifs instead of the stand-alone slides (for example in Jen's story and when showing the web flow)

**Comment by brendajin** [comment]
Amazing change set, thank you!

**Pull request merged**
