### PR TITLE
Adding MD file for Git for Open Source Cheat Sheet, originally create…

### PR DESCRIPTION
**Pull request by cory-wc**
…d by @verythorough

# Summary

Per suggestion from @verythorough, I created a MD version of "Git for Open Source Cheat Sheet".

cc @gdisf/admins

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *teaching-materials* ready!

Built with commit 2bb27610ffcf715ec0f5320886bd1c8a7cd1e2c7

https://deploy-preview-597--teaching-materials.netlify.com

**Comment by verythorough** [comment]
Woot! Thank you @cory-wc! I noticed in the rich diff preview that it's not generating a newline after each of your step headings. 

screenshot_1

If you add an extra empty line between the heading and the text, it should display as expected. Do you have a minute to make this fix? If not, I'm happy to take care of it.

**Comment by cory-wc** [comment]
@verythorough Updated for newlines

**Comment by verythorough** [comment]
Awesome. Looks great!

Thanks again!

**Pull request merged**
