### PR TITLE
[html] combine exercises

### PR DESCRIPTION
**Pull request by kellybelly**
# Summary

Here's a description of changes:

* combine links + images exercises

cc @gdisf/admins

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *teaching-materials* ready!

Built with commit 53397490b7b4ecc6045156535d568e1ac88e58c7

https://deploy-preview-634--teaching-materials.netlify.com

**Comment by trucnguyen** [comment]
Looks good! I like combining the exercises to one slide/breakpoint. Only suggestion is to clearly delineate what we're asking for on the exercise slide.

https://deploy-preview-634--teaching-materials.netlify.com/html/#/39

So instructions could be something like:

- Add at least one image and line break to your page.
- Add links that 1) open in the same window 2) open in a new window and 3) link to an e-mail address.
- Turn the image you added into a link.

**Comment by kellybelly** [comment]
good idea!

**Comment by trucnguyen** [comment]
LGTM!

**Pull request merged**
