### PR TITLE
Added footer to Accessibility slides

### PR DESCRIPTION
**Pull request by norchard**
# Summary

Fixes issue #398

Here's a description of changes:

Added and formatted footer.

cc @gdisf/admins

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit dbf9f772a08da9208252bcff8bed75a38300b964

https://deploy-preview-495--teaching-materials.netlify.com

**Comment by trucnguyen** [comment]
Not seeing it, I think before this happens you'll have to change the theme to the gdilight.css theme. Could you help us change the .js and .css imports to refer to the ../common directory?

**Comment by verythorough** [comment]
Thanks, @norchard! (I love your avatar, btw 😛 ) 

I'm not seeing the footer in the Deploy Preview: https://deploy-preview-495--teaching-materials.netlify.com/accessibility/#/

I think you need to move the footer up above the closing `</div>` tag on line [736](https://deploy-preview-495--teaching-materials.netlify.com/accessibility/#/).

**Comment by norchard** [comment]
@trucnguyen I updated the .js and .css imports to point to ../common. I kept the custom white them instead of changing to the gdilight.css theme because the formatting is particular to that theme. (See screen shots below of gdilight.css theme). I added footer styling from gdilight.css locally to fix the footer styling.

@verythorough (thanks!) The footer code referenced in the issue was actually the wrong footer, so I found the correct footer and moved it above line 736.

screen shot 2017-07-31 at 8 07 51 pm
screen shot 2017-07-31 at 8 08 02 pm

**Comment by trucnguyen** [comment]
Thanks! I will merge! 

Eventually, we'll want all slides to use the gdilight.css theme and the slide formatting shouldn't be specific the light theme nor should there be local css specific to the workshop slides but that's outside the scope of this issue.

Great work @norchard

**Pull request merged**
