### PR TITLE
Update readme filename to README - no need to update link - and…

### PR DESCRIPTION
**Pull request by CrystalFaith**
updated contents in README to match course description. 

Fixes issue [#602](https://github.com/gdisf/teaching-materials/issues/602)  

cc @gdisf/admins
@trucnguyen

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *teaching-materials* ready!

Built with commit d636082076b679158e1b066e75fd2b97610dafbd

https://deploy-preview-605--teaching-materials.netlify.com

**Comment by trucnguyen** [comment]
@CrystalFaith Thanks for renaming the file so it's consistent!

The slides URL is - https://www.teaching-materials.org/tech101/
Let's remove the pricing $15 from the description as well

Looks good!

**Comment by CrystalFaith** [comment]
@trucnguyen - Done and done!

**Comment by trucnguyen** [comment]
LGTM!

**Pull request merged**
