### PR TITLE
deleted github html

### PR DESCRIPTION
**Pull request by estoner-kt**
deleted github html plus any github mentionings in the headings (where it was nessesary)

# Summary

Fixes issue #... 

Here's a description of changes:

* ...
* ...
* ...

_Before you merge, make sure you visually check your changes in the deploy preview. A link to the preview will appear in the PR comments when ready._

cc @gdisf/admins

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit d18a48efc94d91084630d39bc15eb4239387d375

https://deploy-preview-505--teaching-materials.netlify.com

**Comment by verythorough** [comment]
Cool to see these splitting up! Don't forget to update the links on the home page (in /index.html).
Also, since the GitHub slides are removed, students won't get the joke in the last "git push origin hamster" image at the end, so you may want to remove that. :)

**Comment by estoner-kt** [comment]
which links should I update?

**Comment by verythorough** [comment]
In the class listing at `/index.html` (code [here](https://github.com/gdisf/teaching-materials/blob/master/index.html#L217)), I think we'll need to rename the class to "Intro to Git".

**Comment by verythorough** [comment]
Oh, also, if you could edit your summary comment above to include the issue number and description of your changes, that would be a big help to us in reviewing. Thanks!

**Pull request merged**
