### PR TITLE
Deprecate old curriculum

### PR DESCRIPTION
**Pull request by trucnguyen**
There are many variants and outdated curriculum we don't use anymore. This PR separates out the current curriculum/slides we're teaching while preserving and linking to the old stuff

- Split out current curriculum and crusty old curriculum in two separate tables
- Moves old curriculum in /_DEPRECATED/ folder
- Fixes relative links

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview for *teaching-materials* ready!

Built with commit 6ba4e828fb68c59c7e88e2cbcc38ce7aba92dfd8

https://deploy-preview-598--teaching-materials.netlify.com

**Comment by trucnguyen** [comment]
Fixes issue raised in PR #568

**Comment by kellybelly** [comment]
some curriculum is in both current and deprecated
* CSS3 Selectors
* CSS Tools & Techniques
* JS102: JS Arrays, Objects, Functions

can maybe move JS401: Intro to Unit Testing with Jasmine to deprecated?

I also came across some broken links:
* JS102: JS Arrays, Objects, Functions in current
* HTML & CSS (Old, Exercise-Based) in deprecated
* CSS3 Selectors in deprecated
* CSS Tools & Techniques in deprecated
* JS201: JS and the DOM (Review) in deprecated
* PROG102: Intro to Git in deprecated

**Comment by trucnguyen** [comment]
> https://deploy-preview-598--teaching-materials.netlify.com

**Pull request merged**
