### PR TITLE
Fix casing of JavaScript

### PR DESCRIPTION
**Pull request by karlhorky**
# Summary

Here's a description of changes:

* Fix casing of JavaScript in all files

My editor unfortunately stripped whitespace too. You can see the diff without whitespace changes here: https://github.com/gdisf/teaching-materials/pull/642/files?w=1

_Before you merge, make sure you visually check your changes in the deploy preview. A link to the preview will appear in the PR comments when ready._

cc @gdisf/admins

### CODE REVIEW

**Comment by karlhorky** [comment]
not stale

**Comment by karlhorky** [comment]
not stale

**Comment by FrenchBen** [comment]
Thanks for the PR!  
Could you look into the changes needed to make Netlify happy again?`Error: 3 accessibility issues found! Please fix.`

**Comment by karlhorky** [comment]
@FrenchBen I just changed `javascript` and `Javascript` to `JavaScript` (take a look at the diff), so I'm not sure why that would have caused an error there. Probably won't get around to looking at these errors any time soon.

But the **Allow edits by maintainers** switch is on! 👍

**Pull request closed without merging**
