### PR TITLE
[ajax] Convert slides to reveal.js #238

### PR DESCRIPTION
**Pull request by selva-oscura**
# Converted slides to reveal.js and updated links to pull from common directory

Fixes issue # 238 [ajax] Convert slides to reveal.js 

Here's a description of changes:

* converted slides to reveal.js
* converted js and css links to ../common directory
* deleted lib directory
* renamed /img directory to /images and updated index.html links to pull from /images
* downloaded images not hosted locally, placed in /images, and updated links to those images
* tidied up spacing

cc @gdisf/admins

### CODE REVIEW

**Comment by selva-oscura** [comment]
NOTE: Default font size for slides is consistently a bit too large for the amount of content.  
Either text should be redistributed across more slides, the css should be adjust to reduce the default font size (36px to 32px?), or the css should be adjusted to reduce the 'dead space' at the top and sides of the slides.  This was particularly problematic for some of the <pre><code></code></pre> areas because font size caused them to need the scroll bar (while significant amounts space wasted to the left and right) and the standard CTRL-- would not allow the presenter to avoid this problem because the boundaries for the code adjusted proportionately to the changes in font size.

FOR index.html IN THE AJAX DIRECTORY, this sizing problem was addressed by adding css (lines 26-30) to reduce default font size from 36px to 32px.  Please let me know if 'ad hoc' solutions like this are acceptable or whether the original font size should be left untouched or opening an issue to suggest consideration of whether the reveal css in ../common should be adjusted.  Thanks!

**Comment by verythorough** [comment]
Thanks for your work on this!

The one gotcha I found is that the exercises are built on a downloaded copy of `json_starter.html`.  Since they don't download the whole repo, the relative links pointing to `common/` don't work.  We could use CDN links for jQuery and Bootstrap (which we may want to do at some point), but `youtube.js` is a custom-made library.  The best solution I can think of at this point is to make absolute links to http://teaching-materials.org/common/ instead of relative.  I would change this on `json_starter.html`, `json_solution.html`, and `ajax_solution.html`.

With regard to the font sizing, I think your ad hoc solution is great for maintaining functionality for now.  Filing an issue to fix this problem in general is also a good idea.

**Comment by selva-oscura** [comment]
1 - Repeated efforts to verify that link to http://ajaxpatterns.org/Ajax_Gotchas (line 344 of ajax/index.html) was unable to connect. No error message, but just kept cycling until timing out.  (I filed an issue on this, #321)
2 - The requested changes were made.  I see that those updates are showing under the last comment.  Should a new pull request be made or....?

**Comment by verythorough** [comment]
The new commits are added to the existing PR automatically. I'm headed for
the airport, but I can look at this later today and merge it.  Thank you!

**Comment by selva-oscura** [comment]
Thanks. I wasn't quite sure how PRs and new commits worked and didn't want things to slip through the cracks due to that lack of familiarity.

 
 
  On Mon, 8 Aug, 2016 at 6:05, Jessica Parsons<notifications@github.com> wrote:   The new commits are added to the existing PR automatically. I'm headed for
the airport, but I can look at this later today and merge it. Thank you!

**Pull request merged**
