### PR TITLE
Resolved issue #245

### PR DESCRIPTION
**Pull request by rencire**
# Summary

Fixes issue #245 

Here's a description of changes:
- Changed relevant local paths to reference ../common
- Deleted unused local lib folder
- Deleted unused local files

Note:
- Worked with @hahakumquat (Michael Ge)

cc @gdisf/admins

### CODE REVIEW

**Comment by rencire** [comment]
Updated the common 'reveal.js' library because it differs from the local version we used in 'd3/js'.

**Comment by trucnguyen** [comment]
@rencire Can you also update the plugins `markdown`, `marked`  and `highlight` to point to common as well? 
e.g. link to ../common/plugin/markdown/marked.js instead of local

Thanks!

**Comment by rencire** [comment]
@trucnguyen Ok done!

**Comment by trucnguyen** [comment]
LGTM, thanks for updating the reveal library too

**Comment by rencire** [comment]
Hi, the slideshow actually looks incorrect with the current assets under common.  It seems its an issue with using @Yonet's reveal.js library and the current `reveal.css`.  I just took the old assets from d3/ and put them in common instead.

**Comment by brendajin** [comment]
Since a lot of files use the common libs, we're going to need to check the other slides to see how this change affects them

**Comment by rencire** [comment]
ok, it seems #301 will resolve this issue anyway.  I can confirm that at least the d3 slides look correct after applying `reveal.js`, `reveal.min.js`, and `reveal.css` from #301.

**Comment by trucnguyen** [comment]
Thanks for double checking!

**Pull request closed without merging**
