### PR TITLE
[Fixes #244] convert jquery2 slides/dir to common and reveal.js

### LINKED ISSUE #244: [jquery2] Convert slides to reveal.js
Convert the slides from fathom.js to reveal.js in the `jquery2/` directory

# Instructions
- [ ] Use `example/index.html` as a template
- [ ] Add Creative Commons license footer.  See below for snippet.
- [ ] There may be multiple slide decks. Please look at each `*.html` file
- [ ] Use `reveal.js`,  `gdilight` theme from `common/` directory
- [ ] All libs must be from the `common/` directory, including jQuery, Bootstrap, etc
- [ ] Update exercise instructions to also include `common/` directory libs
- [ ] Change all remote images to local inside `jquery2/images/` directory
- [ ] Delete subfolder libraries
- [ ] All slides need to be horizontal
- [ ] Do not include content changes

## Testing
- [ ] Check and make sure the slides look correct on your computer
- [ ] Check that footer includes Creative Commons license image and link

## Footer Snippet
```
<footer>
  <div class="copyright">
  Official class name here -- Chapter name here (if content modified from original) --
  <a rel="license" href="../common/http://creativecommons.org/licenses/by-nc/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/80x15.png" /></a>
  </div>
</footer>
```

### PR DESCRIPTION
**Pull request by tgaff**
# Summary

Fixes issue #244  

Here's a description of changes:

✅  Use example/index.html as a template
✅  Add Creative Commons license footer. See below for snippet.
✅  There may be multiple slide decks. Please look at each `*.html` file
✅  Use reveal.js, gdilight theme from common/ directory
✅  All libs must be from the common/ directory, including jQuery, Bootstrap, etc
⬜  Update exercise instructions to also include `common/` directory libs  
_I didn't find any such instructions, but there were instructions to use `http://teaching-materials.org/jquery2/exercises/jquery.funtext.js`; those were NOT updated.  Also the exercises have link and script tags pointing at `common` on `http://www.teaching-materials.org`.  I've left those in place, because students are directed to download just the *html* file and therefore need to use a CDN of some sort.  (side-note: consider using a CDN for these)_
✅  Change all remote images to local inside jquery2/images/ directory 
  **NOTE: there are a number of images in img that appear to be un-referenced.  Perhaps they should be removed?**
✅  Delete subfolder libraries
❓  All slides need to be horizontal  __All slides were horizontal, however some contain a lot of content (see screenshot).  Should we split this slide?__
⬜ Do not include content changes  __I made one small change that arguably could be considered content.  I added a "click here" link as I found the header-as-link exercise slides to be a little un-clear. These slides contained **only a header** and it seemed rather un-obvious that one should click the header "Exercises".  This change is on it's own commit and could be reverted__
✅ Testing

✅  Check and make sure the slides look correct on your computer  __BUT see comments__
✅  Check that footer includes Creative Commons license image and link

cc @gdisf/admins

### CODE REVIEW

**Comment by tgaff** [comment]
screen shot 2016-07-31 at 4 13 33 pm

Lengthy slide screenshot.  Shall we split this somehow?  (Note that using `li` doesn't help.)

**Comment by brendajin** [comment]
@tgaff thanks for checking the slides visually! Does a `<small>` tag help at all? you could also try taking out the extra `<br>` elements so that everything moves up a bit.

**Comment by tgaff** [comment]
Alright, I've applied small on that slide.  It helped.  Some of the other slides are a little long as well -- they're just content heavy (mostly code).  

Please review at your leisure, @brendajin

**Comment by tgaff** [comment]
*bump*  

@brendajin,  Is there more that you'd like me to do here?

**Comment by brendajin** [comment]
@tgaff sorry for the delay. I'm taking a look now.

**Comment by brendajin** [comment]
Let's keep the unreferenced images for now. I understand what you mean about the Exercise links, thanks for catching that! It's an easy update to make down the line if we want to change it.

Thank you for your help on this!

**Pull request merged**
