### PR TITLE
Adds <br /> after "Ideas"

### PR DESCRIPTION
**Pull request by standardhuman**
# Summary

Fixes issue #479  

Here's a description of changes:

* Adds <br /> after "Ideas"
* ...
* ...

_Before you merge, make sure you visually check your changes in the deploy preview. A line deploy preview. A link to the preview will appear in the PR comments when ready._

cc @gdisf/admins

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit dcbca35d4ce6dc0f446cc3dd98d4d4ce1843b981

https://deploy-preview-500--teaching-materials.netlify.com

**Comment by standardhuman** [comment]
Forgot how to escape html like this: `<br />`

**Comment by trucnguyen** [comment]
LGTM

**Comment by trucnguyen** [comment]
@standardhuman  I have given you another raffle ticket for this PR

**Pull request merged**
