### PR TITLE
[jsoo] update readme, fixes #472

### LINKED ISSUE #472: [jsoo] Update README.md
Please update `README.md` in the `/jsoo/` folder.

- [ ] Find the class title + description [here](https://docs.google.com/document/d/1i3HOT1Mh03S-n3VlwAM6CWXzHlBb_V_QrowEy2jYOHY/edit?usp=sharing) (PRO-TIP: search for `jsoo`).

- [ ] Remove all existing content in `README.md`.

- [ ] Add the following to `README.md`:
```
# {{ CLASS_TITLE }}
```
where `{{ CLASS_TITLE }}` is the class title found in the google doc above.

- [ ] Add the class description found in the google doc above.

- [ ] Check that bolded text, italic text, lists, links are properly formatted.

### PR DESCRIPTION
**Pull request by alfasf**
# Summary

Fixes issue #472  

Here's a description of changes:

* ...Remove all existing content in README.md
* ...Add the class description found in the google doc above.
* ...

_Before you merge, make sure you visually check your changes in the deploy preview. A link to the preview will appear in the PR comments when ready._

cc @gdisf/admins

### CODE REVIEW

**Comment by verythorough** [comment]
Deploy preview ready!

Built with commit 49e4697350cfb7a396aec8794af5907e2462c439

https://deploy-preview-518--teaching-materials.netlify.com

**Comment by alfasf** [comment]
sorry i forgot about the styling but looks good now. Let me know if it needs more changes. 
Thanks,

**Comment by alfasf** [comment]
sorry I forgot all about styling but looks good now. Let me know if it needs more changes. 
Thanks,

**Comment by trucnguyen** [comment]
LGTM, thanks @alfasf

**Pull request merged**
